### PR TITLE
Fix dependency on Vue

### LINKED ISSUE #8: Require vue-chat-scroll returns empty object
after install the latest version with npm:

```
> require('vue-chat-scroll')
{}
```

### PR DESCRIPTION
**Pull request by kylestev**
fixes #8

### CODE REVIEW

**Comment by kylestev** [comment]
Note that this doesn't remove the `devDependency` on Vue `^2.1.10` not sure if it needs that exact build, or if it could be generalized to `^2.1.0`.

**Comment by kylestev** [comment]
Based on the way [`vue-router`](https://github.com/vuejs/vue-router/blob/dev/package.json#L75) and [`vuex`](https://github.com/vuejs/vuex/blob/dev/package.json#L72) have their Vue dependency versioned, I'd say `^2.1.10` is the desired syntax here.

**Comment by kylestev** [comment]
🎉 Thanks! Let me know when a release is cut/published on NPM if you could 😄

**Comment by theomessin** [comment]
@kylestev Version `1.1.1` is out. Let me know if the problem is fixed

**Pull request merged**
