### PR TITLE
Fixes a race condition introduced by rapid scrolling

### PR DESCRIPTION
**Pull request by BenAHammond**

### CODE REVIEW

**Comment by theomessin** [comment]
Tested the code itself and it turns out that something is broken :face_with_head_bandage: I'll have to revert back to version `1.2.1`

**Comment by theomessin** [comment]
Here's a small file to simply test whether the code works: https://gist.github.com/theomessin/3cd47328ac765fc7d37fca001ac65218

If you uncomment line 14 and comment line 15 you will be using your version (which doesn't work).

**Comment by BenAHammond** [comment]
Interesting. Its not having any issues on my copy. I like your test file, let me play with it a bit.

**Comment by BenAHammond** [comment]
Okay, I figured it out. I broke it when I removed the `childList` flag from the MutationObserver. Incoming PR

**Comment by theomessin** [comment]
Any reason to remove the `subtree` flag?

**Pull request merged**
